### ISSUE TITLE
2 or more duplicates not getting removed

### ISSUE THREAD

**Issue by s10wen** [ben-eb/postcss-discard-duplicates#6]
Am I right in thinking;
```
margin-bottom: 24px;
margin-bottom: 1.5rem;
margin-bottom: 24px;
```

should output:
```
margin-bottom: 24px;
```

Currently I'm getting;
```
margin-bottom: 1.5rem;
margin-bottom: 24px;
```

(I'm using this via `https://github.com/ben-eb/cssnano` if that makes a difference)

**Comment by ben-eb** [comment]
Currently we support only exact duplicate removal, there's an open issue for this over at https://github.com/ben-eb/cssnano/issues/86.
