### ISSUE TITLE
None duplicated code getting removed

### ISSUE THREAD

**Issue by s10wen** [ben-eb/postcss-discard-duplicates#7]
I noticed that the following code got removed;
```
.test input[type=text] {
	width: 400px;
	height: 27px;
	padding-left: 12px;
	background-color: #fff;
}
````

I created a reduced test case only using the code above to ensure there were no duplicates and it removed all the code.

(I'm using this via https://github.com/ben-eb/cssnano if that makes a difference)

**Comment by ben-eb** [comment]
Would you be able to share the test case? :smile:

**Comment by s10wen** [comment]
I could, but I'd need to tidy it up and do a few things, any chance you a set up that you drop the above code into a `scss` file, then see what the output is?

**Comment by ben-eb** [comment]
Sure, if the Sass code is self-contained (or you also provide the dependencies).

**Comment by s10wen** [comment]
Could you do it by putting the above `css` code in a self-contained `.scss` file? and remove any dependencies? The output should be the same code, correct? But if the output is nothing, then we know something is a miss. 

Does that make sense, is that right? or am I missing something?

**Comment by ben-eb** [comment]
Basically, I need some CSS that can reproduce the problem you're having. :smile:

(My best guess is that postcss-merge-rules is responsible, so try `{mergeRules: false}` and see if you can reproduce).

**Comment by s10wen** [comment]
CSS is:

```
.test input[type=text] {
    width: 400px;
    height: 27px;
    padding-left: 12px;
    background-color: #fff;
}
```

**Comment by s10wen** [comment]
What the… it doesn't look like it's doing it now, sorry dude, let me test this thoroughly and get back to you :)

**Comment by ben-eb** [comment]
Going to mark this as resolved. Please feel free to re-open if you can reproduce this again. 👍
